### ISSUE TITLE
explanations

### ISSUE THREAD

**Issue by saria85** [jihadbaeth/TwitterSentimentAnalysis#1]
I ran ur code, it seems it extract tweet instantly,
I wanted to compare the result of tweets related one subject in two different country,

do you think its easy to change ur code regard to this

do u have any idea?

thanks

**Comment by jihadbaeth** [comment]
Hi, 

Looking into the JSON schema of retrieved data from the Twitter API, https://dev.twitter.com/overview/api/tweets
you can see that they provide coordinates of the tweet. if that's what you're looking for then I advise you to look into this link https://stackoverflow.com/questions/27122615/twitter4j-search-api-tweets-based-on-location-and-time-interval 
However, I don't think they're being recorded automatically but rather specified by the user manually. So I doubt you would be able to get data at scale. if that's fine with you then you should also look into google's Geocoding API to reflect coordinates into its respective countries. https://developers.google.com/maps/documentation/geocoding/start?csw=1   (limited to 2500 request per day for free usage)
you can also consider extracting user information from their bio or even go one step further and utilize NLP techniques to indicate the location from their timeline (Making a simple location classifier based on hashtags used in old tweets). 

Regards

**Comment by saria85** [comment]
oh tahnks a lot 
you ve been really helpful,

I applied the country , do you know how I can distinguish between cities, for example if I want to compare chicago and missouri?

I tried using google map, but I can get the logitude and latitude of a special place not all the chicago, in this case my result wont be relieble because they are about one street not all the chicago,

thanks for taking the time :)

**Comment by saria85** [comment]
also, may I ask you to help me with the last part of my research

do you know how I can use the result of this to make a training model to evaluate the result?
like the thing we did with supervised approach to get the accuracy , I mean training the model then using the testing data to evaluate,
I believe we can do that here but maybe with more efforts

really thanks for following and helping me

**Comment by jihadbaeth** [comment]
Hi,

This is an example of Google geocoding API response http://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&sensor=true
it has all the information you need. if you don't want to use google geocoding API for some reason then you should take a look at this https://github.com/turgos/Location. easy to setup and works just fine. 
As for the classifier. 

1. Identify the main features (language, hashtags used, times a user is normally active...etc)
2. collect real data from twitter that include coordinates and use it to train your classifier
3. a simple classifier should be good enough (I'm thinking Naive Bayes)

you should take a look at this http://www.programcreek.com/2013/01/a-simple-machine-learning-example-in-java/

good luck with your research

**Comment by saria85** [comment]
I do not know how to appreciate your work and time,
one more question regarding classification,

my main problem about classification is that I was thinking of doing
classification on the result I got from the coreNLP, As you know the result
is, for example, some lines and then get the sentiment of the sentence,
If you mean do classification on that data?

with your explanations it needs again a lot of manual working, I mean
labelling data ...
so whats the benefit? I mean how we can do classification on the result of
the corenlp,

I know I am explaining really badly, I asked this question in the
StackOverflow, no one's answered
I explained there a little better,
this is the link
https://stackoverflow.com/questions/44212814/how-to-do-classification-on-the-result-of-stanford-core-nlp
may I ask you to have a look on that and save me of confusion,

Thank you also very much for your time and help,
saria

**Comment by saria85** [comment]
Really sorry for the many emails :(
I just need to find a way I am totally confused,

do you mean something like this:

https://github.com/anirudh985/TwitterSentimentAnalysis

if so may I ask you to explain how the naive bayes here is related to the
result of the conrenlp search?

thanks,
saria

**Comment by jihadbaeth** [comment]
Hi again, 

I'm sorry but I can't really understand your question. What results are aiming for by doing classification. I'm assuming that since you're looking into using supervised learning techniques then you already have your classes set. otherwise shouldn't you be considering unsupervised learning? 
are you discussing semantics and knowledge extraction from the Twitter feed? if yes, maybe look into this. you should consider looking into academic literature. 
this may be close to what you're looking for 
http://wiki.knoesis.org/index.php/Continuous_Semantic_Crawling_Events

Good luck

**Comment by saria85** [comment]
Thanks for your answer,
Actually I thought stanford classifier should be an unsupervised algorithm,
also I thought it uses the result of corenlp search tweet, to do
classification,

Now I am clear that it is supervised and so I should change my mind,
thanks again,

Regarding location, according to the Twitter api, we can't apply both
location and keywords,
also it mentions in this link:
https://stackoverflow.com/questions/24537099/filtering-tweets-based-on-both-locations-and-track-keywords

there is an approach to do that as mentioned in the aboved link (just three
line),
but I couldnt apply to your code,

may I ask you to have a short short glance on that,
I am under pressure in terms of time, if this part be finished(location) I
can move forward.

I am so sorry for sending many emails :(

**Comment by jihadbaeth** [comment]
why don't you just collect the tweets coming from the feed and then filter them according to location? 
The reason I suggested classification is to link tweets with no geocode to a location. 
Collect data with coming from cities/countries you want to conduct your study upon, extract the tweets features and use them to train your module. then you can assign a location to tweets with no coordinates attached.

**Comment by saria85** [comment]
because I want use the sentiment that core NLP is giving,
I mean, if I extract data of twitter then do filtering like location, I
cant get that file to the corenlp to give me the sentiment,
am I right?

**Comment by jihadbaeth** [comment]
you can still get a sentiment score of every tweet and then assign tweets with no coordinates to a location using your classifier. I just can't see the contradiction here.

**Comment by saria85** [comment]
let explain clearly, as you know I am quite newbie in this field, so I
couldnt find a code that give the file to corenlp then give the sentiment,

all of them are using streaming data,
also I couldnt execute some because they had a lot of dependencies without
using maven and also without explanations,

Is that makes sense?
or still I can use, please let me know
thanks

**Comment by jihadbaeth** [comment]
check the examples show here https://github.com/drewfarris/corenlp-examples/tree/master/src/main/java/drew/corenlp
you still need to add the dependencies to the build path
https://stanfordnlp.github.io/CoreNLP/

**Comment by saria85** [comment]
Hi Jytu,

I appreciate your help,

One more question, when I search keyword like "pizza" and see the sentiment
analysis as 1,2,3,4,
is this number is for positivity negativity in 4 scales?

if so, is there a good reason somebody wanted to change that for healthy
unhealthy data?

I mean, if all researcher work with this 4 scale and they don't change that
for their aim?
In your case what does your sentiment scores means?

thanks for your time and help,
saria

**Comment by jihadbaeth** [comment]
The score ranges from 0-4

1. Very Negative=0
2. Negative=1
3. Neutral=2
4. Positive=3
5. Very Positive=4

you should check their documentation it's pretty good.

**Comment by saria85** [comment]
Jytu,

I greatly appreciate your help,
I finally found one approach, indeed your directions helped me alot, again
thanks for that,

probably the last question, do you know a good preprocessing tools that
accept a file as input then do preprocessing on tweets in the file.
I found some of them that accept just string instead of file,
also another one accept json file as input, my file is txt.

thanks,
saria
